const INVALID_DATA_PASSED_CODE = 400;
const NON_EXISTING_ADDRESS_CODE = 404;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  INVALID_DATA_PASSED_CODE,
  NON_EXISTING_ADDRESS_CODE,
  DEFAULT_ERROR_CODE,
};
