const INVALID_DATA_PASSED_CODE = 400;
const AUTHENTICATION_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NON_EXISTING_ADDRESS_CODE = 404;
const DEFAULT_ERROR_CODE = 500;
const CONFLICT_ERROR_CODE = 409;

module.exports = {
  INVALID_DATA_PASSED_CODE,
  NON_EXISTING_ADDRESS_CODE,
  DEFAULT_ERROR_CODE,
  AUTHENTICATION_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  CONFLICT_ERROR_CODE,
};
